### ISSUE TITLE
 TypeError: Cannot read properties of null (reading 'selector')

### ISSUE THREAD

**Issue by violant** [Shelex/cypress-allure-plugin#104]
Because this error occurred during a after each hook we are skipping all of the remaining tests.
      at displayArg (http://IP/__cypress/tests?p=cypress\support\index.js:7183:29)
      at eval (http://IP/__cypress/tests?p=cypress\support\index.js:7211:47)
      at CypressHandler.started (http://IP/__cypress/tests?p=cypress\support\index.js:7211:30)
      at $Cypress.eval (http://IP/__cypress/tests?p=cypress\support\index.js:7892:34)

**Comment by violant** [comment]
@Shelex  Issue is fixed
