### ISSUE TITLE
TypeError : Cannot read properties of undefined (reading 'onFail')

### ISSUE THREAD

**Issue by sylvain-viole** [Shelex/cypress-allure-plugin#106]
**Describe the bug**
Test run fails with typeError "cannot read properties of undefined (reading 'onFail')"
- Only occurs when `allureLogCypress:true`
- Test passes when allure or allureLogCypress is disabled

**To Reproduce**
1. Activate allure, allureLogCypress
2. pnpm run `cypress open`
3. allure crashes on this cypress command :
```
Cypress.Commands.add("addField", (type, x = 100, y = 100) => {
  // When I add a signature field on first visible image
  cy.findByRole("group")
    .should("exist")
    .then(($viewer) => {
      cy.findAllByRole("img", { container: $viewer, timeout: 20000 })
        .should("exist")
        .first()
        .click(x, y, { force: true });
      cy.findByRole("dialog", { name: "field edition" }).should("exist");
      if (type === "text" || type === "mention" || type === "read_only_text") {
        cy.findByLabelText(`Select sub_text_fields field`).click({
          force: true,
        });
      }
      cy.findByLabelText(`Select ${type} field`).click({ force: true });
    });
});
```

**Expected behavior**
Expected the test run to not fail

**Environment (please complete the following information):**
- package.json :
```
  "devDependencies": {
    "@cucumber/cucumber": "^7.3.1",
    "@shelex/cypress-allure-plugin": "^2.20.1",
    "@testing-library/cypress": "^8.0.2",
    "cucumber-html-reporter": "^5.5.0",
    "cypress": "^8.7.0",
    "cypress-cucumber-preprocessor": "^4.3.0",
    "cypress-fail-fast": "^3.3.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-iframe": "^1.0.1",
    "cypress-mailosaur": "^2.4.0",
    "cypress-terminal-report": "^3.4.0",
    "husky": "^7.0.4",
    "prettier": "^2.4.1",
    "pretty-quick": "^3.1.2"
```
- 
![image](https://user-images.githubusercontent.com/71819292/142895432-682c27c3-10ee-4bab-b550-fe3e0eb4b03b.png)

** Developer Tools Console Output **
```
TypeError: Cannot read properties of undefined (reading 'onFail')
    at commandRunningFailed (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:168482:11)
    at onError (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:168774:9)
From previous event:
    at Object.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:182923:15)
    at Object.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:168782:17)
    at $Cy.cy.<computed> [as then] (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:169952:19)
    at __stackReplacementMarker (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:169260:13)
    at Context.runnable.fn (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:170176:23)
    at callFn (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:122963:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:122950:7)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176739:30
From previous event:
    at Object.onRunnableRun (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176724:19)
    at $Cypress.action (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:166256:28)
    at Test.Runnable.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:174428:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123622:10)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123748:12
    at next (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123531:14)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123541:7
    at next (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123443:14)
    at Hook.<anonymous> (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123504:7)
    at next (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176649:24)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176678:13
From previous event:
    at onNext (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176675:59)
    at done (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:122903:5)
    at callFn (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:122986:7)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:122950:7)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176739:30
From previous event:
    at Object.onRunnableRun (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:176724:19)
    at $Cypress.action (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:166256:28)
    at Hook.Runnable.run (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:174428:13)
    at next (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123465:10)
    at https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:123509:5
    at timeslice (https://qa-kalos-app.yousign.tech/__cypress/runner/cypress_runner.js:117435:27)
```

thanks !

**Comment by Shelex** [comment]
Hi @sylvain-viole 
Thank you for reporting an issue.

Unfortunately I don't see what may cause some other plugins to throw such error.

Only thing I can suggest - please open chrome developer tools, and execute in console `localStorage.debug = 'allure-plugin*'` in order to enable debug logs for this plugin. At least we could specify the exact state when error occurs.

In case you cannot prepare a repository where I can reproduce it, but still need help with this issue - you can contact me by email `ovr.shevtsov@gmail.com`.

**Comment by sylvain-viole** [comment]
Thanks!
Here is the result with allure debugger :
![image](https://user-images.githubusercontent.com/71819292/142903419-6a14e104-894b-4369-b7f2-7e57aa8ccef1.png)

- any clue with maybe ?
```
CypressHandler.js:142 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
```
- Or
```
allure-plugin:mocha EVENT_TEST_FAIL: Add a signer 
```

**Comment by Shelex** [comment]
> allure-plugin:mocha EVENT_TEST_FAIL: Add a signer

Thanks for reply.
Yeah, I mean second one: `allure-plugin:mocha EVENT_TEST_FAIL: Add a signer `
it means that allure-plugin just received event that test failed (as it is listening to mocha events) and some plugin (or your code) trying to read onFail property. Now need to understand why disabling cypress logger fixes it :)

**Comment by Shelex** [comment]
@sylvain-viole Okay, it seems I have found the cause - I am checking if argument is a native object, however one of properties is a jquery object which may fail to parse properly.
Could you please check v2.22.0 where it should be resolved?

**Comment by sylvain-viole** [comment]
@Shelex : Yep it works !

Nice !

What was it all about ?
Object that causes failure was indeed a jquery object (javascriptTestingLibrary)

Anyway, many thanks for your fix! that was fast ! :)

**Comment by Shelex** [comment]
> @Shelex : Yep it works !
> 
> Nice !
> 
> What was it all about ? Object that causes failure was indeed a jquery object (javascriptTestingLibrary)
> 
> Anyway, many thanks for your fix! that was fast ! :)

I guess that jquery object may contain functions, circular object, anyway is quite huge, so that should be definitely limited in printing, that's why I have used util.inspect with flags that limiting depth and size, instead of json.stringify with custom replacer that can handle just case whith circular dependencies.

Anyway, glad that it helped, thanks for raising!
