### ISSUE TITLE
Webpack compilation error: Can't resolve util in \node_modules\@shelex\cypress-allure-plugin\reporter\allure-cypress

### ISSUE THREAD

**Issue by jprealini** [Shelex/cypress-allure-plugin#115]
Versions:
Cypress 9.0
Node 16.13
Webpack 5.64.1
TScript 4.4.4

Hi

I am trying to make the cypress-allure-plugin work in my Cypress project, but I am getting an error. I followed the configuration instructions in the main repo's readme, but when I run cypress I get this:

```
Oops...we found an error preparing this test file:

  cypress\support\index.ts

The error was:

Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'util' in 'C:\Projects\seed-ui-cypress-project\node_modules\@shelex\cypress-allure-plugin\reporter\allure-cypress'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

Module not found: Error: Can't resolve 'path' in 'C:\Projects\seed-ui-cypress-project\node_modules\@shelex\cypress-allure-plugin\reporter'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
    at handle (C:\Projects\seed-ui-cypress-project\node_modules\@cypress\webpack-preprocessor\dist\index.js:180:23)
    at finalCallback (C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:436:32)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:500:17
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\Hook.js:18:14)
    at Cache.storeBuildDependencies (C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Cache.js:122:37)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:496:19
    at Hook.eval [as callAsync] (eval at create (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:493:23
    at Compiler.emitRecords (C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:885:39)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:485:11
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:867:14
    at Hook.eval [as callAsync] (eval at create (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Projects\seed-ui-cypress-project\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:864:27
    at C:\Projects\seed-ui-cypress-project\node_modules\neo-async\async.js:2818:7
    at done (C:\Projects\seed-ui-cypress-project\node_modules\neo-async\async.js:3522:9)
    at alreadyWritten (C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:696:8)
    at C:\Projects\seed-ui-cypress-project\node_modules\webpack\lib\Compiler.js:784:19
    at C:\Projects\seed-ui-cypress-project\node_modules\graceful-fs\graceful-fs.js:123:16

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```
This is what my tsconfig.json looks like>
```
{
  //TODO:VM Come back and clean up this list.
  "compilerOptions": {
    "target": "es2016", /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "module": "commonjs", /* Specify what module code is generated. */
    "outDir": "./dist", /* Specify an output folder for all emitted files. */
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
    "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
    "strict": true, /* Enable all strict type-checking options. */
    "noImplicitAny": false, /* Enable error reporting for expressions and declarations with an implied `any` type.. */
    "skipLibCheck": true, /* Skip type checking all .d.ts files. */
    "types": [
      "cypress",
      "../node_modules/@shelex/cypress-allure-plugin/reporter"
    ]
  },
  "include": [
    "../node_modules/@shelex/cypress-allure-plugin/reporter",
    "../node_modules/cypress",
    "**/*.ts"
  ],
  "exclude": [
    "../cypress/dist/"
  ]
}
```

My plugins/index.js file:

```
/// <reference types="cypress" />
/// <reference types="@shelex/cypress-allure-plugin" />

const allureWriter = require('@shelex/cypress-allure-plugin/writer');
const cypressTypeScriptPreprocessor = require('./cy-ts-preprocessor');
const setBrowserDownloadDirectory = require('./set-browser-download-directory');
const setBaseUrl = require('./set-base-url');

/**
 * @type {Cypress.PluginConfig}
 */

module.exports = async (on, config) => {
    await setBaseUrl(config);
    on('file:preprocessor', cypressTypeScriptPreprocessor);
    on('before:browser:launch', setBrowserDownloadDirectory);
    allureWriter(on, config);

    return config;
};
```
And this is my support/index.ts file
**one thing to note. I am importing custom commands from a "cypress-core" package I created, which holds shared page objects and custom commands that are used accross different projects... Not sure if this could be interefering with the plugin's configuration**

```

/// <reference types="./index" />

import '@shelex/cypress-allure-plugin';
// Don't change!!
// These are required imports from the cypress-core package
import '../../node_modules/cypress-core/support/commands/api-login-command'
import '../../node_modules/cypress-core/support/commands/cookies-command'
import '../../node_modules/cypress-core/support/commands/get-cy-command'
import '../../node_modules/cypress-core/support/commands/get-identity-cookies-command'
import '../../node_modules/cypress-core/support/commands/local-storage-command'
import '../../node_modules/cypress-core/support/commands/login-command'
import '../../node_modules/cypress-core/support/commands/logout-command'
import '../../node_modules/cypress-core/support/commands/user-permissions'
import '../../node_modules/cypress-core/support/commands/users-intercept'
import '../../node_modules/cypress-core/support/commands/profile-intercept'

// Import your custom commands files below this line



// Don't change anything below this line

Cypress.config('integrationFolder', 'cypress/integration')

```
Any hint on what could be causing this?

Thanks!!

**Comment by Shelex** [comment]
Hi @jprealini 
Thank you for posting an issue.

I guess you don't even need any `cy-ts-preprocessor` at all since cypress 4.x has it as in-built feature.
Could you please check it without file preprocessing?

**Comment by jprealini** [comment]
@Shelex Thanks! I hadn't realized that. So I removed the cy-ts-preprocessor loading, and everything works as expected now... 
Awesome! Thanks again!
