### ISSUE TITLE
Failure with exception when using cypress-allure-plugin with @badeball/cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by pwpatton** [Shelex/cypress-allure-plugin#139]
**Describe the bug**
When attempting to use [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin) with  [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) an exception is thrown causing the first test to fail and cypress appears to hang. Hence no allure-results are generated

**To Reproduce**
- clone my example repo here [badeball-cypress-cucumber-allure-issue](https://github.com/pwpatton/badeball-cypress-cucumber-allure-issue)
- npm install
- npm run cy:open and run all tests
- open the developer tools window and see stacktrace

```
Uncaught TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'keyword')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at CucumberHandler.checkLinksInExamplesTable (https://duckduckgo.com/__cypress/tests?p=cypress\support\index.ts:1862:43)
    at Runner.eval (https://duckduckgo.com/__cypress/tests?p=cypress\support\index.ts:2878:39)
From previous event:
    at onNext (https://duckduckgo.com/__cypress/runner/cypress_runner.js:185685:19)
    at done (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129431:5)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:129496:11
From previous event:
    at callFn (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129494:14)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129478:7)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:185755:30
From previous event:
    at Object.onRunnableRun (https://duckduckgo.com/__cypress/runner/cypress_runner.js:185740:19)
    at $Cypress.action (https://duckduckgo.com/__cypress/runner/cypress_runner.js:174847:28)
    at Test.Runnable.run (https://duckduckgo.com/__cypress/runner/cypress_runner.js:183404:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://duckduckgo.com/__cypress/runner/cypress_runner.js:130150:10)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130276:12
    at next (https://duckduckgo.com/__cypress/runner/cypress_runner.js:130059:14)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130069:7
    at next (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129971:14)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130037:5
    at timeslice (https://duckduckgo.com/__cypress/runner/cypress_runner.js:123963:27)
```
**Expected behavior**
A successful test run with allure-results.

### Test code to reproduce
[badeball-cypress-cucumber-allure-issue](https://github.com/pwpatton/badeball-cypress-cucumber-allure-issue)

See README.md to see steps to duplicate

**Environment (please complete the following information):**
- Cypress version:                                9.6.1
- OS:                                                   Windows 11
- Node version:                                   v14.17.3

**Additional context**
I originally created an issue for [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) here [714](https://github.com/badeball/cypress-cucumber-preprocessor/issues/714)

Note this comment on the issue:
https://github.com/badeball/cypress-cucumber-preprocessor/issues/714#issuecomment-1128134280

**Comment by DeChrish** [comment]
@Shelex  any plans to fix this issue?

**Comment by pwpatton** [comment]
Hi @Shelex, I've updated this issue with a simpler example repo to duplicate.

**Comment by kenzhemir** [comment]
Faced this issue as well sadly

**Comment by Shelex** [comment]
Have added support for [@badeball/cypress-cucumber-preprocessor](https://www.npmjs.com/package/@badeball/cypress-cucumber-preprocessor) internals in v2.27.0.
But I will heavily rely on your feedback, as again - I have not managed to make it work yet, excepting example repo provided for this issue.

**Comment by DeChrish** [comment]
@Shelex Allure report is working  - @pwpatton  pl check from your end.
Thanks for the quick fix.

**Comment by kenzhemir** [comment]
Hi!

I updated allure plugin to v2.27.0 and [@badeball/cypress-cucumber-preprocessor](https://www.npmjs.com/package/@badeball/cypress-cucumber-preprocessor) to v11.3.1

Some tests are passing, but some don't and I get this error message:

```
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'id')    

at eval (domain/__cypress/tests?p=cypress/support/index.ts:4245:70)    
at Array.find (<anonymous>)    
at CucumberHandler.get currentScenario [as currentScenario] (domain/__cypress/tests?p=cypress/support/index.ts:4244:57)    
at CucumberHandler.checkLinksInExamplesTable (domain/__cypress/tests?p=cypress/support/index.ts:4303:18)    
at Runner.eval (domain/__cypress/tests?p=cypress/support/index.ts:5306:39)From previous event:    
at onNext (domain/__cypress/runner/cypress_runner.js:185716:19)    
at done (domain/__cypress/runner/cypress_runner.js:129431:5)    
at domain/__cypress/runner/cypress_runner.js:129496:11
```

Error points at approximately this [line](https://github.com/Shelex/cypress-allure-plugin/blob/master/reporter/allure-cypress/CucumberHandler.js#L34)
I think it doesn't pass for scenarios that have *Background* like this:

```
Feature: Feature name
	Background:
		Given some user
	Scenario: Scenario name
		When ...
		Then ...
```

If u need more details, I can search for it
