### ISSUE TITLE
Webpack compilation error: react-scripts v5/webpack 5 causing webpack errors in \node_modules\@shelex\cypress-allure-plugin\reporter

### ISSUE THREAD

**Issue by elainedcb** [Shelex/cypress-allure-plugin#142]
**Describe the bug**
We're getting compilation errors when running the tests with the plugin
```
Error: Webpack Compilation Error
--
70 | Module not found: Error: Can't resolve 'path' in '/apps/node_modules/@shelex/cypress*allure*plugin/reporter'
71 |  
72 | BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
73 | This is no longer the case. Verify if you need this module and configure a polyfill for it.
74 |  
75 | If you want to include a polyfill, you need to:
76 | * add a fallback 'resolve.fallback: { "path": require.resolve("path*browserify") }'
77 | * install 'path*browserify'
78 | If you don't want to include a polyfill, you can use an empty module like this:
79 | resolve.fallback: { "path": *** }
80 | at handle (/apps/node_modules/@cypress/webpack*preprocessor/dist/index.js:180:23)
81 | at finalCallback (/apps/node_modules/webpack/lib/Compiler.js:441:32)
82 | at /apps/node_modules/webpack/lib/Compiler.js:505:17
83 | at /apps/node_modules/webpack/lib/HookWebpackError.js:68:3
84 | at Hook.eval [as callAsync] (eval at create (/apps/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
85 | at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/apps/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
86 | at Cache.storeBuildDependencies (/apps/node_modules/webpack/lib/Cache.js:122:37)
87 | at /apps/node_modules/webpack/lib/Compiler.js:501:19
88 | at Hook.eval [as callAsync] (eval at create (/apps/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
89 | at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/apps/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
90 | at /apps/node_modules/webpack/lib/Compiler.js:498:23
91 | at Compiler.emitRecords (/apps/node_modules/webpack/lib/Compiler.js:919:5)
92 | at /apps/node_modules/webpack/lib/Compiler.js:490:11
93 | at /apps/node_modules/webpack/lib/Compiler.js:885:14
94 | at Hook.eval [as callAsync] (eval at create (/apps/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
95 | at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/apps/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
96 | at /apps/node_modules/webpack/lib/Compiler.js:882:27
97 | at /apps/node_modules/neo*async/async.js:2818:7
98 | at done (/apps/node_modules/neo*async/async.js:3522:9)
99 | at Hook.eval [as callAsync] (eval at create (/apps/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
100 | at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/apps/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
101 | at /apps/node_modules/webpack/lib/Compiler.js:736:33
```
This happens since we've upgraded `react-scripts` to the latest stable version 5 and to webpack v5 and along with the update, webpack 5 no longer polyfills node.js core modules. One of them, `path-browserify` is affected which I assume a dependency/called within the plugin. The errors do not happen if we remove the reporter plugin.

As an interim solution, we manually added the the fallback in the webpack plugin in the `plugins/index.js` file to support this
```
resolve: {
    fallback: {
      path: require.resolve('path-browserify'),
    },
  }
```

Will there be any way that compatible modules be updated to have webpack 5 support the plugin?

Thank you!

**Comment by Shelex** [comment]
I have explicitly switched to using `path-browserify` as direct dependency instead of 'path', so should be resolved. 
Could you please check if v2.27.0 works for your case?
