### ISSUE TITLE
ReferenceError: AllureWriter is not defined

### ISSUE THREAD

**Issue by oddbookworm** [Shelex/cypress-allure-plugin#148]
Cypress 10.3.1

Ran `npm i -D @shelex/cypress-allure-plugin`
Updated `cypress.config.js` to
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://the-internet.herokuapp.com/',
    // baseUrl: 'http://localhost:7080/',

    setupNodeEvents(on, config) {
      AllureWriter(on, config);
      return config;
    }
  }
});
```
Added `import '@shelex/cypress-allure-plugin';` to `cypress/support/e2e.js`

Ran `npx cypress run --env allure=true` 

Following full traceback:
```
Your configFile threw an error from: E:\QA Engineering Stuff\the-internet-cypress\cypress.config.js

The error was thrown while executing your e2e.setupNodeEvents() function:

ReferenceError: AllureWriter is not defined
    at setupNodeEvents (E:\QA Engineering Stuff\the-internet-cypress\cypress.config.js:9:7)
    at C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:118:14
    at tryCatcher (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\node_modules\bluebird\js\release\method.js:39:29)    
    at RunPlugins.load (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:115:9)
    at RunPlugins.runSetupNodeEvents (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:254:10)
    at EventEmitter.<anonymous> (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:185:22)
    at EventEmitter.emit (events.js:400:28)
    at process.<anonymous> (C:\Users\andre\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (events.js:400:28)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

My package.json content:
```
{
  "name": "the-internet-cypress",
  "version": "1.0.0",
  "description": "Cypress testing of https://the-internet.herokuapp.com/",
  "main": "index.js",
  "scripts": {
    "cypress:open": "cypress open"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cypress": "^10.3.1"
  },
  "devDependencies": {
    "@shelex/cypress-allure-plugin": "^2.28.0"
  }
}
```

I am unsure as to what I did wrong in installing the plugin.

**Comment by Shelex** [comment]
@oddbookworm 
Have you imported \ added require of AllureWriter module in your `cypress.config.js`?
```js
const allureWriter = require('@shelex/cypress-allure-plugin/writer');
// import allureWriter from "@shelex/cypress-allure-plugin/writer";
```

**Comment by oddbookworm** [comment]
Oof, that was the problem... thank you!
