### ISSUE TITLE
Error Loading the reporter: cypress-allure-plugin

### ISSUE THREAD

**Issue by Rana-Shabbir** [Shelex/cypress-allure-plugin#191]
While executing this command:
`npx cypress run --headed --browser chrome --spec cypress/e2e/testSuite.cy.js --env allure=true`

Error:

Error loading the reporter: cypress-allure-plugin

We searched for the reporter in these paths:

 - C:\Users\rana\Desktop\Circadia\webportal-end-to-end-automation\rough_work\billing-module-end-to-end-automation-with-cypress\cypress-allure-plugin
 - C:\Users\rana\Desktop\Circadia\webportal-end-to-end-automation\rough_work\billing-module-end-to-end-automation-with-cypress\node_modules\cypress-allure-plugin

Learn more at https://on.cypress.io/reporters

Error: Cannot find module 'C:\Users\rana\Desktop\Circadia\webportal-end-to-end-automation\rough_work\billing-module-end-to-end-automation-with-cypress\node_modules\cypress-allure-plugin'
Require stack:
- C:\Users\rana\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\packages\server\lib\reporter.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at PackherdModuleLoader._tryResolveFilename (C:\Users\rana\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\node_modules\@packages\packherd-require\dist\loader.js:650:32)
    at PackherdModuleLoader._resolvePaths (C:\Users\rana\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\node_modules\@packages\packherd-require\dist\loader.js:491:31)
    at PackherdModuleLoader.tryLoad (C:\Users\rana\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\node_modules\@packages\packherd-require\dist\loader.js:421:40)
    at Module._load (C:\Users\rana\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\node_modules\@packages\packherd-require\dist\require.js:87:74)
    at i._load (<embedded>:2760:53545)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at S.loadReporter (<embedded>:2765:19452)
    at C.initializeReporter (<embedded>:2812:337518)
    at C.startWebsockets (<embedded>:2812:337822)
    at C.open (<embedded>:2812:336147)
    at async v.create (<embedded>:2812:348236)
    at async O (<embedded>:2812:427285)
    at async W (<embedded>:2812:438701)
 
 @Shelex

**Comment by Shelex** [comment]
@Rana-Shabbir please follow the documentation: https://github.com/Shelex/cypress-allure-plugin#installation

As I see you receive some error from cypress `server\lib\reporter.js` and it mentions `Error loading the reporter`, whilte technically for cypress it is a regular plugin (and not a reporter).

And it is covered in installation section:
> There is no need to set this plugin as reporter in Cypress or use any other allure reporters.

Hope it helps

**Comment by Rana-Shabbir** [comment]
> @Rana-Shabbir please follow the documentation: https://github.com/Shelex/cypress-allure-plugin#installation
> 
> As I see you receive some error from cypress `server\lib\reporter.js` and it mentions `Error loading the reporter`, whilte technically for cypress it is a regular plugin (and not a reporter).
> 
> And it is covered in installation section:
> 
> > There is no need to set this plugin as reporter in Cypress or use any other allure reporters.
> 
> Hope it helps

> Thank you now it worked fine

**Comment by Rana-Shabbir** [comment]
Thank you @Shelex now it worked fine
