### ISSUE TITLE
Module exports doesn't work correct with typescript

### ISSUE THREAD

**Issue by Grosha** [Shelex/cypress-allure-plugin#71]
**Describe the bug**
There is an error when trying to connect the allure plugin with cypress in plugin/index.ts file and the project is on the typescript.

1. Connect plugin with import in plugin/index.ts file `import allureWriter from "@shelex/cypress-allure-plugin/writer";`
2. Run cypress `npx cypress open`
3. Error

 ```
**Message:** The function exported by the plugins file threw an error.

We invoked the function exported by `~/project/cypress/plugins/index.ts`, but it threw an error.

**Details:** TypeError: writer_1.default is not a function
    at ~/project/cypress/plugins/index.ts:25:15
    at /Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:89:12
    at tryCatcher (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:86:7)
    at EventEmitter.<anonymous> (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:200:5)
    at EventEmitter.emit (node:events:365:28)
    at process.<anonymous> (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (node:events:365:28)
    at process.emit (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Stack trace:**
```
Error: The function exported by the plugins file threw an error.

We invoked the function exported by `~/project/cypress/plugins/index.ts`, but it threw an error.
    at Object.get (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:968:15)
    at EventEmitter.<anonymous> (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:144:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/andrii/Library/Caches/Cypress/6.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

```

**Expected behavior**
Cypress runner start working

It works if import all library:
`import * as allureWriter from "@shelex/cypress-allure-plugin/writer";`

**Environment:**
- OS: Mac 
- Cypress package version: 6.3.0
- Cypress binary version: 6.3.0
- Electron version: 11.2.0
- Bundled Node version: 12.18.3
- node 16.0.0

**Comment by Shelex** [comment]
For now upgraded docs with info how to connect library to project using `import` syntax, as it may require providing breaking changes for existing projects.
