### ISSUE TITLE
Cypress component tests fail when running with cypress-allure-plugin

### ISSUE THREAD

**Issue by ssv-w32** [Shelex/cypress-allure-plugin#75]
**Short description**
Cypress component tests fail when running with cypress-allure-plugin

**Steps to reproduce**
1. Add simple ct test for Vue application
```
import { mount } from '@cypress/vue'
import Button from '../../../src/common/components/Button/Button.vue'

// eslint-disable-next-line no-undef
it('should render slots in default state', () => {
  mount(Button, {
    slots: {
      default: 'TEST CONTENT',
      icon: '<span id="fake_icon"/>'
    }
  })
  // eslint-disable-next-line no-undef
  cy.get('button')
    .contains('Test button')
    .click()
})
```
2. Set allure-plugin

```
//support/index.js

import '@shelex/cypress-allure-plugin'
```

```
// plugins/index.js

module.exports = (on, config) => {
  on('dev-server:start', options => {
    return startDevServer({
      options,
      webpackConfig
    })
  })

  allureWriter(on, config)
  return config
}
```

```
//cypress.json

{
  "testFiles": "**/*.spec.js",
  "componentFolder": "cypress/integration/component",
  "video": false,
  "env": {
    "allure": true,
    "allureResultsPath": "cypress/integration/component/allure-results"
  }
}

```

3. Run tests: `npx cypress run-ct`

```
  1) An uncaught error was detected outside of a test

  0 passing (320ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read property 'replace' of undefined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object.eval (webpack:///./node_modules/@shelex/cypress-allure-plugin/node_modules/mkdirp/lib/use-native.js?:4:25)
      at eval (webpack:///./node_modules/@shelex/cypress-allure-plugin/node_modules/mkdirp/lib/use-native.js?:12:30)
      at Object../node_modules/@shelex/cypress-allure-plugin/node_modules/mkdirp/lib/use-native.js (http://localhost:33029/__cypress/src/js/0.js:267:1)
      at __webpack_require__ (http://localhost:33029/__cypress/src/main.js:64:30)
      at eval (webpack:///./node_modules/@shelex/cypress-allure-plugin/node_modules/mkdirp/index.js?:6:36)
      at Object../node_modules/@shelex/cypress-allure-plugin/node_modules/mkdirp/index.js (http://localhost:33029/__cypress/src/js/0.js:201:1)
      at __webpack_require__ (http://localhost:33029/__cypress/src/main.js:64:30)
      at eval (webpack:///./node_modules/@shelex/cypress-allure-plugin/node_modules/allure-js-commons/dist/src/writers/AllureWriter.js?:5:18)
      at Object../node_modules/@shelex/cypress-allure-plugin/node_modules/allure-js-commons/dist/src/writers/AllureWriter.js (http://localhost:33029/__cypress/src/js/0.js:154:1)
      at __webpack_require__ (http://localhost:33029/__cypress/src/main.js:64:30)
```

**Expected behavior**
Test should pass, allure-results should be generated as usual

**Environment:**
- Cypress version:                                7.5.0
- Cypress-allure-plugin version:           2.5.1
- cypress/vue version:                          2.2.3
- cypress/webpack-dev-server:            1.3.1
- OS:                                                    Ubuntu 18.04.2 LTS

**Additional information**
Switching off allure plugin fixes the issue. This only reproduces for component tests in Cypress (`run-ct` command).

**Comment by ssv-w32** [comment]
Hi @Shelex, 
did you have a chance to look through this issue?

**Comment by Shelex** [comment]
Hi @ssv-w32 
Yes, I am able to reproduce it, however I think it is due to some webpack configuration, as it seems that build target is browser and it throws error for some node-related package inside allure-js-commons.
Fixing or workaround investigation will require some time.

**Comment by ssv-w32** [comment]
@Shelex , thank you! Will test it asap and let you know.

**Comment by ssv-w32** [comment]
@Shelex,

Fix works fine, thank you!
