### ISSUE TITLE
TypeError: Converting circular structure to JSON in my specific custom commands after plugin update into ^2.15 version

### ISSUE THREAD

**Issue by OSnuszka** [Shelex/cypress-allure-plugin#91]
**Describe the bug**

Cypress started failed after the plugin update into 2.15 version. I'm using a custom command which one chooses a random element from a group selector (choosing multiple elements). It's works normally until plugin actualization.

**To Reproduce**
1. Use plugin version 2.15 or higher
2. Provide custom cypress command
```
Cypress.Commands.add('any', { prevSubject: 'element' }, (subject, size = 1) => {
  cy.wrap(subject).then((elementList) => {
    elementList = elementList.jquery ? elementList.get() : elementList;
    elementList = Cypress._.sampleSize(elementList, size);
    elementList = elementList.length > 1 ? elementList : elementList[0];
    cy.wrap(elementList);
  });
});
```
3. Use it like `cy.get(selector).**any()**;
4. It will fail

![image](https://user-images.githubusercontent.com/78599192/134653664-a3207b0f-2ff2-4acc-8aff-d1da41e67702.png)

Currently, I'm using version 2.14

**Expected behavior**

**Environment (please complete the following information):**
- Cypress version:                               ^2.15
- OS:                                                     Windows | Mac | Linux (distro):

** Developer Tools Console Output **
```
<!-----------------------------------------------------------------------------------------------

Converting circular structure to JSON
    --> starting at object with constructor 'HTMLElement'
    |     property '_vent' -> object with constructor 'a'
    --- property 'root' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLElement'
    |     property '_vent' -> object with constructor 'a'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at displayArg (https://author.hcpportal.dev.opengarden.rch.cm/__cypress/tests?p=cypress/support/index.js:3678:33)
    at eval (https://author.hcpportal.dev.opengarden.rch.cm/__cypress/tests?p=cypress/support/index.js:3685:50)
    at AllureReporter.cyCommandStart (https://author.hcpportal.dev.opengarden.rch.cm/__cypress/tests?p=cypress/support/index.js:3685:33)
    at $Cypress.eval (https://author.hcpportal.dev.opengarden.rch.cm/__cypress/tests?p=cypress/support/index.js:2766:31)

------------------------------------------------------------------------------------------------->
```

**Comment by Shelex** [comment]
Hi @OSnuszka
Thank you for opening an issue. 
Should be resolved in 2.16.1
